### ISSUE TITLE
[Bug] Maskbook post image based post / comment function down on Facebook

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1158]
# Bug Report

As the recent update 1.10.20, we fixed the basic Maskbook post encrypt post functionality on fb.

There are still several bugs to fix
- [x] auto paste for fb comment
- [x]  post image based post 
- [ ]  post (all payload) post still down on Mobile  

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by Jack-Works** [comment]
fixed for desktop, imo it will also works for mobile

**Comment by Tedko** [comment]
Let’s publish a fix ver to store and test on mobile as well?

**Comment by Tedko** [comment]
`Maskbook # released 835dfb2 测完了，Auto Paste 没有触发，和上一版是一样的，加密之后会弹出窗口要求拷贝密文。` Mobile not fixed yet

**Comment by Tedko** [comment]
tested on Version 1.10.21 on chrome. Not fixed yet. Wait for testing new version

**Comment by Tedko** [comment]
Tested Version 1.11.1. Comment autopaste is fixed, so is image payload

<img width="675" alt="Screen Shot 2020-06-15 at 21 12 17" src="https://user-images.githubusercontent.com/6687437/84661448-f28e2a80-af4c-11ea-807d-e71423b6833e.png">
